### PR TITLE
Feedback 3/6

### PR DESCRIPTION
**Pull request by courtneyjacinic**
I addressed all changes I could. The ones I wasn't certain how to approach are flagged in the feedback document here: https://docs.google.com/document/d/1PRMP93pCLEc0JcdUlzXI7EZ7ppmOspPWS_teeqHns3E/edit

### CODE REVIEW

**Review by juliazbyron — APPROVED** [review]

**Review by juliazbyron — APPROVED** [review]

**Review by juliazbyron — APPROVED** [review]

**Review by juliazbyron — APPROVED** [review]

**Review by juliazbyron — CHANGES_REQUESTED** [review]
~~Do you think this should follow the same format of the others where it has something like "Make sure before you foster you can ___"?~~ Scratch that comment, I see the updated version now

**Review by juliazbyron — APPROVED** [review]

**Review by juliazbyron — APPROVED** [review]

**Review by juliazbyron — APPROVED** [review]

**Review by juliazbyron — APPROVED** [review]

**Review by juliazbyron — APPROVED** [review]

**Review by juliazbyron — APPROVED** [review]

**Review by juliazbyron — APPROVED** [review]

**Review by juliazbyron — CHANGES_REQUESTED** [review]
Do you think saying "develop any behavioral issues" sounds too ominous? Plus I think fostering helps to resolve behavioral issues from stress of being in the shelter, so developing behavioral issues didn't sound like a risk. I remember them saying that usually it's that animals have to get used to each other, so maybe something about that would be better?

**Review by juliazbyron — APPROVED** [review]

**Review by juliazbyron — APPROVED** [review]

**Comment by courtneyjacinic** [comment]
@juliazbyron 
Re: "If your animals or your foster animals have or develop any behavioral issues or illnesses, they may need to be separated for each other's safety and well-being."

Maybe try:
Until your animals and foster animals get used to each other or in case one gets sick, they may need to be separated for each other's safety and well-being.

**Comment by juliazbyron** [comment]
@courtneyjacinic That works. ~~Do you want to update the HTML file or should I?~~ I made the change

**Pull request merged**
